In [2]:
import pandas as pd
import numpy as np

In [3]:
crime = pd.read_csv('state_crime.csv')

In [4]:
crime.head()

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
0,Alabama,2015,4858979,2978.9,725.6,2040.7,212.7,472.4,328.3,7.2,...,94.9,144746,35255,99156,10335,22952,15954,348,2039,4611
1,Alabama,2016,4863300,2947.8,700.5,2006.3,241.1,532.3,388.2,8.4,...,96.4,143362,34065,97574,11723,25886,18877,407,1916,4686
2,Alabama,2017,4874747,2957.3,645.7,2048.1,263.4,524.2,387.8,8.3,...,86.5,144160,31477,99842,12841,25551,18902,404,2028,4217
3,Alabama,2018,4887871,2817.2,590.1,1958.9,268.3,519.6,387.6,7.8,...,83.4,137700,28841,95747,13112,25399,18944,383,1996,4076
4,Alabama,2019,4903185,2674.4,531.9,1886.1,256.5,510.8,381.0,7.3,...,80.4,131133,26079,92477,12577,25046,18679,358,2068,3941

In [11]:
columns_to_keep= ['State','Year', 'Data.Population',"Data.Rates.Violent.All"]
crime= pd.read_csv('state_crime.csv', usecols=columns_to_keep)

In [5]:
# checking for missing values
crime.isnull().sum()

State                            0
Year                             0
Data.Population                  0
Data.Rates.Property.All          0
Data.Rates.Property.Burglary     0
Data.Rates.Property.Larceny      0
Data.Rates.Property.Motor        0
Data.Rates.Violent.All           0
Data.Rates.Violent.Assault       0
Data.Rates.Violent.Murder        0
Data.Rates.Violent.Rape          0
Data.Rates.Violent.Robbery       0
Data.Totals.Property.All         0
Data.Totals.Property.Burglary    0
Data.Totals.Property.Larceny     0
Data.Totals.Property.Motor       0
Data.Totals.Violent.All          0
Data.Totals.Violent.Assault      0
Data.Totals.Violent.Murder       0
Data.Totals.Violent.Rape         0
Data.Totals.Violent.Robbery      0
dtype: int64

In [6]:
# checking for duplicates
crime.duplicated().sum()

0

In [19]:
# filtering to only keep the year between 2015-2019
years_to_keep= list(range(2015,2019))
crime_filtered = crime[crime['Year'].isin(years_to_keep)]

In [22]:
years_to_drop= [str(year) for year in range(1960, 2019)]
crime_filtered = crime.drop(columns=[col for col in crime.columns if col in years_to_drop])
print(crime_filtered)

        State  Year  Data.Population  Data.Rates.Violent.All
0     Alabama  2015          4858979                   472.4
1     Alabama  2016          4863300                   532.3
2     Alabama  2017          4874747                   524.2
3     Alabama  2018          4887871                   519.6
4     Alabama  2019          4903185                   510.8
...       ...   ...              ...                     ...
2890  Wyoming  2015           586107                   222.1
2891  Wyoming  2016           585501                   244.2
2892  Wyoming  2017           579315                   237.5
2893  Wyoming  2018           577737                   212.2
2894  Wyoming  2019           578759                   217.4

[2895 rows x 4 columns]

In [23]:
crime_filtered.to_csv('filtered_crime_data.csv', index=False)